image: docker

build_test_images:
  stage: build
  tags:
    - 40c
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE --pull .
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:experimental
    - docker push $CI_REGISTRY_IMAGE:experimental

search:
  image: docker:dind
  stage: test
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY/cn-tsn/project/dbas/dbas/db:development
    - docker pull $CI_REGISTRY/cn-tsn/project/dbas/dbas:development
    - docker pull $CI_REGISTRY_IMAGE:experimental
    - docker network create -d bridge dbas_$CI_JOB_ID
    - docker run -d --name db_$CI_JOB_ID --net=dbas_$CI_JOB_ID --env-file ./development.env $CI_REGISTRY/cn-tsn/project/dbas/dbas/db:development
    - sleep 8  # init dbas' database
    - docker run -d --name web_$CI_JOB_ID --net=dbas_$CI_JOB_ID --env-file ./development.env -e DB_HOST=db_$CI_JOB_ID -e SEARCH_NAME=search_$CI_JOB_ID $CI_REGISTRY/cn-tsn/project/dbas/dbas:development
    - docker run -d --name search_$CI_JOB_ID --net=dbas_$CI_JOB_ID --env-file ./development.env -e DBAS_HOST=web_$CI_JOB_ID -e DB_HOST=db_$CI_JOB_ID $CI_REGISTRY_IMAGE:experimental
    - sleep 25  # wait for elasticsearch to start up and pull data from dbas' database via dbas
  script:
    - docker exec search_$CI_JOB_ID nosetests --with-coverage --cover-package=core --cover-xml -w . core -v
  after_script:
    - docker kill db_$CI_JOB_ID web_$CI_JOB_ID search_$CI_JOB_ID || true
    - docker network rm dbas_$CI_JOB_ID || true
  coverage: '/^TOTAL\s*\d+\s*\d+\s*(\d+\%)\s*$/'
  artifacts:
    paths:
      - coverage.xml
    expire_in: 10 mins

sonar:
  image: hhucn/sonar-scanner
  stage: deploy
  script:
    - sonar-scanner -D sonar.host.url=https://sonarqube.cs.uni-duesseldorf.de -D sonar.login=$SONARQUBE_LOGIN -D sonar.projectKey=$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME -D sonar.projectName=$CI_PROJECT_NAME -D sonar.projectVersion=1 -D sonar.sources=. -D sonar.python.coverage.reportPath=coverage.xml
  only:
    - develop
  when: always

deploy_image:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master

deploy_dev_image:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:development
    - docker push $CI_REGISTRY_IMAGE:development
  only:
    - develop