image: docker

stages:
  - build
  - test
  - deploy

.job-template: &add-services
  services:
    - name: $CI_REGISTRY_IMAGE:testing
      alias: elasticsearch
    - name: $CI_REGISTRY/cn-tsn/project/dbas/dbas:development
      alias: dbas
      command: ["/bin/bash", "-c", "'alembic upgrade head ; pserve development.ini --reload'"]
    - name: $CI_REGISTRY/cn-tsn/project/dbas/dbas/db:testing
      alias: db

  image: python:3-alpine
  variables:
    DBAS_HOST: dbas
    DBAS_PORT: 4284
    DBAS_DB_HOST: db
    DBAS_DB_PORT: "5432"
    DBAS_DB_USER: "postgres"
    DBAS_DB_PW: "DXxCNtfnt!MOo!f8LY1!P%sw3KGzt@s!"
    DBAS_AUTHN_SECRET: "89#s3cr3t_15"

# ------------------------------------------------------------------------------
# Job definitions

build_test_image:
  stage: build
  tags:
    - 40c
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE --pull .
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:testing
    - docker push $CI_REGISTRY_IMAGE:testing

flake8:
  image: python:3-alpine
  stage: test
  script:
    - pip3 install --quiet flake8
    - flake8 .
  allow_failure: true

unit:
  <<: *add-services
  stage: test
  script:
    - cd search_service
    - pip3 install nose coverage
    - pip3 install -r requirements.txt
    - nosetests --with-coverage --cover-package=search_service --cover-xml search_service
  coverage: '/^TOTAL\s*\d+\s*\d+\s*(\d+\%)\s*$/'
  artifacts:
    paths:
      - coverage.xml
    expire_in: 10 mins

deploy_image:
  stage: deploy
  tags:
    - 40c
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master

deploy_dev_image:
  stage: deploy
  tags:
    - 40c
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:develop
    - docker push $CI_REGISTRY_IMAGE:develop
  only:
    - develop