version: '3'
services:
  search:
    build: .
    ports:
      - "9200:9200"
      - "5000:5000"

    environment:
      APPLICATION_HOST: ${DBAS_HOST}
      APPLICATION_PORT: ${DBAS_PORT}
      APPLICATION_PROTOCOL: ${DBAS_PROTOCOL}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PW}

    volumes:
      - ./core/analysis/synonyms_english.txt:/usr/share/elasticsearch/config/synonyms_english.txt
      - ./core/analysis/synonyms_german.txt:/usr/share/elasticsearch/config/synonyms_german.txt
      - .:/code/

networks:
  default:
    external:
      name: dbas_default
