version: '3'
services:
  search:
    build: .
    ports:
      - "9200:9200"
      - "5000:5000"

    environment:
      - DBAS_HOST=web
      - DBAS_PORT=4284
      - PROTOCOL=http

    volumes:
      - ./search_service/analysis/synonyms_english.txt:/usr/share/elasticsearch/config/synonyms_english.txt
      - ./search_service/analysis/synonyms_german.txt:/usr/share/elasticsearch/config/synonyms_german.txt
      - .:/code/

networks:
  default:
    external:
      name: dbas_default
