version: '3'
services:
  search:
    build: .
    ports:
      - "9200:9200"
      - "5000:5000"

    env_file:
      - development.env

    volumes:
      - ./core/analysis/synonyms_english.txt:/usr/share/elasticsearch/config/synonyms_english.txt
      - ./core/analysis/synonyms_german.txt:/usr/share/elasticsearch/config/synonyms_german.txt
      - .:/code/

networks:
  default:
    external:
      name: dbas_default
